### PR TITLE
updated polish translation for newly added items

### PR DESCRIPTION
**Pull request by streetwraith**

### CODE REVIEW

**Comment by Argent77** [comment]
Thank you. But I will upload more item-related updates in the next few days.

I leave this PR open in case you want to translate the new lines as well.

**Comment by streetwraith** [comment]
Sure, I'm happy to help.
BTW I am the author of this comment https://forums.beamdog.com/discussion/comment/1196596/#Comment_1196596
My plan is to try and add all those missing items to your code as I think this is a good way for me to learn weidu etc.

**Comment by Argent77** [comment]
@streetwraith The update with more NPC-related items has been uploaded: 9bfd67bd0eb29d0459c71bf123e55ede55b346bc

New lines for translation can be found in dialog.tra, misc.tra, and the readme.html.

**Comment by streetwraith** [comment]
Added the missing polish translations, also translated some more sections of the readme.
I've tried to make some of the translations properly gendered, but couldn't find any info on how to parametrize WeiDU strings to include the alternate versions in dialogF.tlk... so for now all the translations are just gender neutral.

**Comment by Argent77** [comment]
Thank you. I'd prefer to have the Credits section in the Readme in English though. Otherwise, it's more difficult for me to make changes without having to consult the translators.

About female strings, they are added directly after the male string definition. Example:
```
@1234 = ~I'm a man of my word.~  ~I'm a woman of my word.~
```
For several character-specific attributes there are [tokens](https://gibberlings3.github.io/iesdp/appendices/token_lists/bgeetokens.htm) which take care of the details. The above example could be shortened to this:
```
@1234 = ~I'm a <PRO_MANWOMAN> of my word.~ 
```

**Comment by Argent77** [comment]
Thank you!

**Pull request merged**
